import { imgMultibeneficios, imgBlanqueamiento, imgNatural, imgFamiliar, imgSensibilidad, imgInfantil } from './Images';


export const Multibeneficios = {
  "footer": "Multibeneficios",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgMultibeneficios.cabecera,
    tituloSuperior: "Colgate",
    prefijo: "",
    nombre: "TOTAL 12",
    sufijo: "",
    subTitulo: "12 Horas de protección contra 12 problemas bucales.",
    informacion: "",
    tituloSec: "ayuda a",
    beneficios: [
      { beneficio: "Prevenir las caries" },
      { beneficio: "Proteger las encías" },
      { beneficio: "Prevenir la formación de sarro" },
      { beneficio: "Prevenir la formación de placa" },
      { beneficio: "Combatir las bacterias" },
      { beneficio: "Combatir el mal aliento" },
      { beneficio: "Remover las mancha de los dientes" },
      { beneficio: "Fortalecer el esmalte dental" },
      { beneficio: "Prevenir las caries en raíces expuestas" },
      { beneficio: "Prevenir la pérdida mineral de los dientes" },
      { beneficio: "Prevenir problemas de encías causados por bacterias" },
      { beneficio: "Limpia aún entre dientes" }
    ],
    extra: "",
    productos: []
  },
  "ImagenesMenuBotones": imgMultibeneficios.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_01,
      tituloSuperior: "Colgate TOTAL 12",
      prefijo: "",
      nombre: "CLEAN MINT",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "",
      beneficios: [
        { beneficio: "Para una salud bucal completa que te protege más allá de los dientes, reduciendo bacterias en lengua, mejillas y encías hasta por 12 horas*" },
      ],
      extra: "*Con cuatro (4) semanas de uso continuo",
      productos: []
    },
    {
      id: 2,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_02,
      tituloSuperior: "Colgate TOTAL PROFESSIONAL",
      prefijo: "",
      nombre: "SALUD VISIBLE",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "",
      beneficios: [
        { beneficio: "Adicionada con tecnología que cambia de color ayudándote a reducir la formación de placa y bacterias para una salud bucal completa* que hasta un odontólogo podrá ver." },
      ],
      extra: "*Reduce bacterias en dientes, lengua, mejillas y encías; ayuda a reducir la placa que causa problemas en las encías, fortalece el esmalte y ayuda a aliviar la sensibilidad con el uso continuo.",
      productos: []
    },
    {
      id: 3,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_03,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "ENCÍAS REFORZADAS",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "beneficios:",
      beneficios: [
        { beneficio: "Tecnología avanzada con mineral Complex." },
        { beneficio: "Construye una barrera que refuerza tus encías contra bacterias." },
        { beneficio: "Mientras la fórmula va limpiando toda la boca para mantenerla saludable." },
      ],
      extra: "*Causado por bacterias **Hasta 12H de protección contra bacterias y el mal aliento con el uso continuo por 4 semanas.v",
      productos: []
    },
    {
      id: 4,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_04,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "PROFESSIONAL",
      sufijo: "",
      subTitulo: "ALIENTO SALUDABLES",
      informacion: "Adicionada con tecnología Neutro-Odor* que ayuda a neutralizar el mal aliento causado por bacterias, para brindarte una salud bucal completa",
      tituloSec: "",
      beneficios: [
        { beneficio: "Tecnología Neutro-Odor es parte del sabor." },
        { beneficio: "Reduce bacterias en dientes, lengua, mejilla y encías, ayuda a reducir la placa que causa problemas en las encías, fortalece el esmalte y ayuda a aliviar la sensibilidad con el uso continuo." },
        { beneficio: "Vs Total Whitening." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 5,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_05,
      tituloSuperior: "Colgate 360°",
      prefijo: "",
      nombre: "ADVANCED TOTAL 12",
      sufijo: "",
      subTitulo: "",
      informacion: "Limpieza saludable en toda tu boca limpiador de lengua y mejillas con diseño innovador, remueve bacterias en cuatro áreas:",
      tituloSec: "",
      beneficios: [
        { beneficio: "Dientes" },
        { beneficio: "Lengua" },
        { beneficio: "Mejillas" },
        { beneficio: "Encías" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 6,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_06,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "ENJUAGUE CLEAN MINT",
      sufijo: "",
      subTitulo: "12 horas de defensa activa Protege dientes, lengua y encías",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Fórmula con CPC + Zinc" },
        { beneficio: "Eficaz contra la placa" },
        { beneficio: "Combate bacterias y mal aliento" },
        { beneficio: "Cero alcohol" },
        { beneficio: "Salud Bucal Completa" },
        { beneficio: "Combate bacterias y ácidos" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 7,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_07,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "ENJUAGUE ANTI SARRO",
      sufijo: "",
      subTitulo: "",
      informacion: "Prueba la nueva Colgate Total 12 Anti Sarro, nueva fórmula con micropartículas que limpian y combaten la formación de sarro y te brindan 12 horas de protección activa contra bacterias.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Fórmula con CPC + Zinc" },
        { beneficio: "Hasta 12 horas de defensa activa contra bacterias y placa" },
        { beneficio: "Previene la formación de sarro" },
        { beneficio: "Combate el mal aliento" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 8,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_08,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "ENJUAGUE ENCÍAS REFORZADAS",
      sufijo: "",
      subTitulo: "",
      informacion: "Cuida la salud de tu boca con el nuevo enjuague bucal Colgate Total 12 Encías Reforzadas que brinda hasta 12 horas de protección antibacterial para encías más saludables*. El enjuague bucal sin alcohol ayuda a fortalecer y prevenir problemas en las encías** mientras combate el mal aliento para que puedas tener una salud bucal completa todos los días.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Fórmula con CPC + Zinc" },
        { beneficio: "Hasta 12 horas de defensa activa contra bacterias y placa**" },
        { beneficio: "Enjuague bucal sin alcohol" },
        { beneficio: "Combate el mal aliento" },
        { beneficio: "Protege hasta el 100% de tus encías contra las bacterias." },
      ],
      extra: "*vs. sólo cepillado **causados por bactérias",
      productos: []
    },
    {
      id: 9,
      tipo: "producto",
      img: imgMultibeneficios.producto.prodMultibeneficios_09,
      tituloSuperior: "Colgate TOTAL",
      prefijo: "",
      nombre: "SPRAY BUCAL",
      sufijo: "",
      subTitulo: "",
      informacion: "Protección en cualquier momento y lugar, con agente antibacterial, para una boca más fresca y protegida, en cualquier momento y lugar. ¡Sólo aplica y listo!",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Fórmula con CPC + Zinc" },
        { beneficio: "Hasta 12 horas de defensa activa contra bacterias y placa" },
        { beneficio: "Spray oral con agente antibacterial gracias a su fórmula avanzada" },
        { beneficio: "que ofrece protección al contacto con bacterias." },
        { beneficio: "Combate el mal aliento y ofrece protección en cualquier momento y lugar." },
        { beneficio: "Siente tu aliento fresco por más tiempo" },
        { beneficio: "Su tamaño es práctico y fácil de usar" },
        { beneficio: "Uso diario. Excelente rendimiento : 100 usos" },
      ],
      extra: "",
      productos: []
    },
  ]
}

export const Blanqueamiento = {
  "footer": "Blanqueamiento",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgBlanqueamiento.cabecera,
    tituloSuperior: "Colgate",
    prefijo: "",
    nombre: "LUMINOUS WHITE",
    sufijo: "",
    subTitulo: "Un tono más blanco en una semana*",
    informacion: "",
    tituloSec: "beneficios",
    beneficios: [
      { beneficio: "Sus microcristales aceleradores de blanqueamiento contienen ingredientes similares a los usados por los dentistas." },
      { beneficio: "Combina abrillantadores ópticos para blanquear los dientes instantáneamente." },
    ],
    extra: "",
    productos: []

  },
  "ImagenesMenuBotones": imgBlanqueamiento.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_01,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "LUMINOUS WHITE",
      sufijo: "",
      subTitulo: "Un tono más blanco en una semana*",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Sus microcristales aceleradores de blanqueamiento contienen ingredientes" },
      ],
      extra: "*Mediante el cepillado con crema dental Colgate Luminous White vs crema dental regular con flúor.",
      productos: []

    },
    {
      id: 2,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_02,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "LUMINOUS WHITE INSTANT",
      sufijo: "",
      subTitulo: "Dientes blancos al instante*",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Su inovadora tecnología ahora combina abrillantadores ópticos para blanquear los dientes instantáneamente*" },
      ],
      extra: "*Efecto blanqueador instantáneo es temporal",
      productos: []

    },
    {
      id: 3,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_03,
      tituloSuperior: "Colgate",
      prefijo: "LUMINOUS WHITE",
      nombre: "CARBÓN ACTIVADO",
      sufijo: "",
      subTitulo: "Sonrisa visiblemente deslumbrante con tecnología con Carbón Activado",
      informacion: "Sonrisa más blanca en una semana. Colgate Luminous White quiere dar al mundo sonrisas brillantes y hermosas que destaquen y celebren la belleza única, esa belleza que refleja la confianza, la personalidad y la actitud. Muestra la belleza de tu deslumbrante sonrisa con la tecnología de Luminous White + Carbón Activado",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Blanquea tus dientes" },
        { beneficio: "Remoción de manchas" },
        { beneficio: "Poderosa tecnología para la remoción de manchas y una sonrisa blanca" },
      ],
      extra: "",
      productos: []

    },
    {
      id: 4,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_04,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "MAX WHITE",
      sufijo: "",
      subTitulo: "Una nueva dimensión de blancura para una sonrisa espectacular",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Combate gérmenes por 12 horas" },
        { beneficio: "Aliento fresco" },
        { beneficio: "Máxima protección anticaries" },
        { beneficio: "Fortalece y blanquea tus dientes" },
      ],
      extra: "",
      productos: []

    },
    {
      id: 5,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_05,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "360° ADVANCED",
      sufijo: "LUMINOUS WHITE",
      subTitulo: "Para una limpieza más completa de toda tu boca.",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Copas removedoras de manchas." },
        { beneficio: "Cerdas pulidoras exclusivas." },
        { beneficio: "Limpiador de lengua y mejillas único y punta limpiadora elevada." },
        { beneficio: "Diseño avanzado y limpieza efectiva y cómoda." },
      ],
      extra: "*Ayuda a remover manchas efectivamente, con cerdas pulidoras mas copa blanqueadora.",
      productos: []

    },
    {
      id: 6,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_06,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "360° LUMINOUS WHITE",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Copas removedoras de manchas" },
        { beneficio: "Cerdas pulidoras exclusivas" },
        { beneficio: "Limpiador de lengua" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 7,
      tipo: "producto",
      img: imgBlanqueamiento.producto.prodBlanqueamiento_07,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "Enjuague Luminous White",
      sufijo: "",
      subTitulo: "Sonrisa brillante, boca fresca.",
      informacion: "Ayuda a mantener el blanco natural de los dientes y refresca el aliento",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Asegura una sonrisa brillante y una boca siempre fresca." },
      ],
      extra: "*Para obtener los mejores resultados, utilice la línea completa de Colgate Luminous White.",
      productos: []
    },
  ]
}

export const Natural = {
  "footer": "Natural",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgNatural.cabecera,
    tituloSuperior: "Colgate",
    prefijo: "",
    nombre: "NATURAL EXTRACTS",
    sufijo: "",
    subTitulo: "",
    informacion: "Te sorprenderá con las propiedades de sus ingredientes de origen natural. Te da una explosión de sabor para el cuidado de tu sonrisa en tres presentaciones: “Cítricos y Eucalipto” “Coco y Jengibre” y “Carbón Activado y Menta",
    tituloSec: "AYUDA A:",
    beneficios: [
      { beneficio: "Remover las bacterias que pueden causar mal aliento, caries o problemas de encías con el cepillado regular." },
    ],
    extra: "",
    productos: []
  },
  "ImagenesMenuBotones": imgNatural.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_01,
      tituloSuperior: "Colgate Naturals Extracts",
      prefijo: "",
      nombre: "DEFENSA REFORZADA",
      sufijo: "",
      subTitulo: "CÍTRICOS & EUCALIPTO",
      informacion: "Su combinación única de ingredientes naturales y lo mejor de la ciencia de Colgate te ayudan a fortalecer tus dientes y te brinda una sensación natural de frescura.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Explosión de sabores para el cuidado de tu sonrisa." },
        { beneficio: "Contiene extractos de limón, lima, naranja y eucalipto con un toque de hierbabuena que ayudan a fortalecer los dientes y refrescar su boca." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 2,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_02,
      tituloSuperior: "Colgate Naturals Extracts",
      prefijo: "",
      nombre: "DETOX",
      sufijo: "",
      subTitulo: `COCO & JENGIBRE Protege tu sonrisa & llénala de vida.`,
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Explosión de sabores para el cuidado de tu sonrisa" },
        { beneficio: "Contiene extractos naturales de aceite de coco y jengibre que ayudan a eliminar bacterias que causan el mal aliento, la caries y problemas de encías." },
        { beneficio: "El sabor del jengibre proporciona una sensación refrescante" },
        { beneficio: "El aceite de coco proporciona una sensación suave y dulce" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 3,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_03,
      tituloSuperior: "Colgate Naturals Extracts",
      prefijo: "",
      nombre: "PURIFICANTE",
      sufijo: "",
      subTitulo: "CARBÓN ACTIVADO & MENTA",
      informacion: "",
      tituloSec: "",
      beneficios: [
        { beneficio: "Los científicos de Colgate, después de años de investigación, han combinado el carbón activado y la menta, en una exclusiva fórmula con espuma activa que ayuda a eliminar las impurezas* y proteger tus dientes" },
      ],
      extra: "*Con cepillado regular",
      productos: []
    },
    {
      id: 5,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_04,
      tituloSuperior: "Colgate Naturals Extracts",
      prefijo: "",
      nombre: "CÚRCUMA & HIERBABUENA",
      sufijo: "",
      subTitulo: "",
      informacion: "Combinamos la frescura de la yerbabuena con el sabor sorprendente de la cúrcuma en el nuevo lanzamiento de Colgate Naturals Extracts Cúrcuma y Yerbabuena.",
      tituloSec: "",
      beneficios: [
        { beneficio: "Su fórmula desarrollada con la más alta tecnología ayuda a eliminar de modo natural las bacterias en tu boca manteniendo el aliento fresco por mucho más tiempo." },
        { beneficio: "Sorpréndete con esa nueva pasta de dientes y siente una experiencia única" },
      ],
      extra: "",
      productos: []
    },

    {
      id: 4,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_05,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "ZERO MENTA",
      sufijo: "",
      subTitulo: "",
      informacion: "Nuestra nueva crema dental Colgate Zero Menta mantiene tus dientes sanos, fortalece su esmalte dental y proporciona protección anticaries, clínicamente comprobada.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Con 0% de saborizantes, endulzantes, conservadores y colorantes artificiales. Vegana y libre de gluten." },
        { beneficio: "Sabor natural menta para un aliento fresco y duradero." },
        { beneficio: "Brinda protección a tus dientes y una limpieza profunda con la fórmula de la pasta de dientes en gel transparente con sabor a menta." },
        { beneficio: "Ideal para una sonrisa perfecta con aliento fresco y duradero todos los días, previniendo las caries en los dientes." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 6,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_06,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "ZERO HIERBABUENA",
      sufijo: "",
      subTitulo: "",
      informacion: "Siéntete confiado y seguro dejando tu boca saludable con la crema dental Colgate Zero Hierbabuena con sabor a 100% natural.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Con 0% de saborizantes, endulzantes, conservadores y colorantes artificiales. Vegana y libre de gluten." },
        { beneficio: "Sabor natural menta para un aliento fresco y duradero." },
        { beneficio: "Brinda protección a tus dientes y una limpieza profunda con la fórmula de la pasta de dientes en gel transparente con sabor a menta." },
        { beneficio: "Ideal para una sonrisa perfecta con aliento fresco y duradero todos los días, previniendo las caries en los dientes." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 7,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_07,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "Pro Planet Whitening",
      sufijo: "",
      subTitulo: "Sé parte del cambio con el innovador cepillo de dientes Colgate Pro Planet, elaborado con 80% menos de plástico *.",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Contiene un mango de aluminio de larga duración" },
        { beneficio: "Cabeza reemplazable con cerdas pulidoras y blanqueadoras que remueven las manchas, para una sonrisa más brillante." },
        { beneficio: "Diseñado para limpiar partes de la boca, que otros cepillos no pueden alcanzar**" },
        { beneficio: "Limpia los dientes, lengua, mejillas y encías." },
      ],
      extra: "*vs. cepillo de dientes ordinario. ** vs. otros cepillos planos ordinario.",
      productos: []
    },
    {
      id: 8,
      tipo: "producto",
      img: imgNatural.producto.prodNatural_08,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "BAMBOO",
      sufijo: "",
      subTitulo: "Bueno para el medio ambiente y bueno para ti",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Mango elaborado con bambú 100% natural - 100% Biodegradable " },
        { beneficio: "El bambú que usamos es elaborado de forma responsable, usando métodos de cultivos sostenibles Empaque de cartón reciclable" },
        { beneficio: "Mango cubierto con ingredientes naturales para prevenir humedad" },
        { beneficio: "Las cerdas son suaves, con infusión de carbón y sales de bambú* para una limpieza efectiva" },
      ],
      extra: "",
      productos: []
    },
  ]
}

export const Familiar = {
  "footer": "Familiar",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgFamiliar.cabecera,
    tituloSuperior: "Colgate",
    prefijo: "",
    nombre: "TRIPLE ACCIÓN",
    sufijo: "",
    subTitulo: "Triple protección para toda su familia",
    informacion: "",
    tituloSec: "BENEFICIOS:",
    beneficios: [
      { beneficio: "Extra blancura" },
      { beneficio: "Protección anticaries" },
      { beneficio: "Aliento fresco" },
    ],
    extra: "",
    productos: []
  },
  "ImagenesMenuBotones": imgFamiliar.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_01,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "MÁXIMA PROTECCIÓN ANTICARIES",
      sufijo: "",
      subTitulo: "",
      informacion: "Su fórmula con fluoruro activo penetra en sus dientes para retener el calcio natural haciéndolos tan fuertes como puedan ser.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Ayuda a combatir las caries, inclusoentre los dientes" },
        { beneficio: "Fortalece y limpia lo dientes" },
        { beneficio: "Delicioso sabor refrescante" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 2,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_02,
      tituloSuperior: "Colgate Triple Acción",
      prefijo: "",
      nombre: "MENTA ORIGINAL",
      sufijo: "",
      subTitulo: "¡Limpieza profunda y triple protección!",
      informacion: "Con la Crema Dental Colgate Triple Acción protege tu salud bucal y la de toda tu familia, bríndandoles la confianza que necesitan",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Su poderosa fórmula anticaries ayuda a eliminar las pequeñas bacterias que se encuentran entre las mejillas, dientes y lengua dejando una sensación totalmente refrescante en tu boca por varias horas." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 3,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_03,
      tituloSuperior: "Colgate Triple Acción",
      prefijo: "",
      nombre: "X-TRA BLANCURA",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "ofrece multiprotección para una sonrisa extraordinaria con su formula con extra micro-partículas pulidoras para dientes más blancos y para la protección de tu salud bucal y la de toda tu familia." },
        { beneficio: "Obtén triple beneficio: Protección, Xtra Blancura, y Frescura." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 4,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_04,
      tituloSuperior: "Colgate Triple Acción",
      prefijo: "",
      nombre: "X-TRA FRESCURA",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Micro - cristales que brinda una sensación de frescura de larga duración y protección de tu salud bucal y la de toda tu familia." },
        { beneficio: "Obtén triple beneficio: Protección, Blancura, y Extra Frescura*." },
      ],
      extra: "",
      productos: []
    },
    {
      id: 5,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_06,
      tituloSuperior: "Colgate Plax",
      prefijo: "",
      nombre: "SOFT MINT",
      sufijo: "",
      subTitulo: "",
      informacion: "Colgate Plax Soft Mint mata los gérmenes que causan la gingivitis, la placa bacteriana y el mal aliento hasta por 12 horas.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Ayuda a reducir hasta el 99% de los gérmenes" },
        { beneficio: "Aliento fresco" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 6,
      tipo: "producto",
      img: imgFamiliar.producto.prodFamiliar_05,
      tituloSuperior: "Cepillo Dental Colgate",
      prefijo: "",
      nombre: "TRIPLE ACCIÓN",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Ayuda a remover delicadamente las manchas a revelar el blanco natural de los dientes" },
        { beneficio: "Efectiva remoción de la placa bacteriana" },
        { beneficio: "Refresca el aliento" },
      ],
      extra: "",
      productos: []
    },
  ]
}

export const Sensibilidad = {
  "footer": "Sensibilidad",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgSensibilidad.cabecera,
    tituloSuperior: "Colgate Sensitive",
    prefijo: "",
    nombre: "PRO-ALIVIO",
    sufijo: "",
    subTitulo: "Alivio intantáneo y duradero de la sensibilidad.",
    informacion: "",
    tituloSec: "BENEFICIOS:",
    beneficios: [
      { beneficio: "Exclusiva fórmula Pro-Argin" },
      { beneficio: "Alivio Instantáneo (Con aplicación directa)" },
      { beneficio: "Alivio duradero (Con cepillado diario)" },
    ],
    extra: "",
    productos: []
  },
  "ImagenesMenuBotones": imgSensibilidad.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_01,
      tituloSuperior: "Colgate Sensitive Pro-Alivio",
      prefijo: "",
      nombre: "REAL WHITE",
      sufijo: "",
      subTitulo: "Alivio instantáneo* y duradero** de la sensibilidad más blanqueadora.",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Exclusiva fórmula Pro-Argin \u2122" },
        { beneficio: "Fórmula de baja abrasión suave y elimina eficazmente las manchas,ayudando a restablecer la blancura natural de los dientes" },
      ],
      extra: "*Con aplicación directa **Con un cepillado diario",
      productos: []
    },
    {
      id: 2,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_02,
      tituloSuperior: "Colgate Sensitive Pro-Alivio",
      prefijo: "",
      nombre: "REPARACIÓN COMPLETA",
      sufijo: "",
      subTitulo: "Alivio intantáneo* y duradero contra la sensibilidad",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Exclusiva fórmula Pro-Argin \u2122" },
        { beneficio: "Su fórmula sella los túbulos expuestos para el alivio instantáneo y duradero de la sensibilidad" },
        { beneficio: "Con el uso regular, el zinc ayuda a fortalecer la encía para reducir la recesión que exponen los túbulos de los dientes que generan |a sensibilidad." },
        { beneficio: "Clínicamente comprobado" },
      ],
      extra: "*Con aplicación directa, masajeando cada diente sensible durante 1 minuto.",
      productos: []
    },
    {
      id: 3,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_03,
      tituloSuperior: "Colgate Sensitive",
      prefijo: "",
      nombre: "PRO-ALIVIO",
      sufijo: "",
      subTitulo: "ORIGINAL",
      informacion: "Alivio instantáneo* y duradero** de la sensibilidad",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Exclusiva fórmula Pro-Argin \u2122" },
      ],
      extra: "*Con aplicación directa **Con un cepillado diario",
      productos: []
    },
    {
      id: 4,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_04,
      tituloSuperior: "Colgate Sensitive",
      prefijo: "",
      nombre: "BLANQUEADORA",
      sufijo: "",
      subTitulo: "Alivio de la sensibilidad dental clínicamente comprobado",
      informacion: "Su fórmula ayuda a aliviar la sensibilidad del diente y un sistema blanqueador que ayuda a combatir la formación del sarro y remover suavemente las manchas dejando sus dientes más blancos.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Sabor refrescante" },
        { beneficio: "Ayuda a remover manchas" },
        { beneficio: "Protección comprobada" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 5,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_06,
      tituloSuperior: "Colgate Sensitive Pro-Alivio",
      prefijo: "",
      nombre: "INMEDIATO",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "",
      beneficios: [
        { beneficio: "Fórmula clínicamente comprobada y desarrollada con el poder de la tecnología de arginina para una acción inmediata y eficaz contra las molestias causadas por la sensibilidad en los dientes." },
        { beneficio: "Con el uso regular, se crea una barrera de larga duración que actúa como un escudo protector contra la sensibilidad dental" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 6,
      tipo: "producto",
      img: imgSensibilidad.producto.prodSensibilidad_05,
      tituloSuperior: "Colgate Sensitive Pro-Alivio",
      prefijo: "",
      nombre: "INMEDIATO ENCÍAS",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "",
      beneficios: [
        { beneficio: "Alivio inmediato de la sensibilidad y prevención de problemas de encías." },
        { beneficio: "Poderosa tecnología de arginina y doble zinc." },
        { beneficio: "Con el uso continuo, crea un escudo protector para tus encías evitando la retracción." },
      ],
      extra: "",
      productos: []
    },
    {
        id: 7,
        tipo: "imagenes",
        tituloSec: "",
        productos: [
            {
                tituloSuperior: "Colgate SlimSoft",
                nombre: "ADVANCED",
                img: imgSensibilidad.producto.prodSensibilidad.prodSensibilidad_071,
            },
            {
                tituloSuperior: "Colgate",
                nombre: "SLIMSOFT",
                img: imgSensibilidad.producto.prodSensibilidad.prodSensibilidad_072,
            },
            {
                tituloSuperior: "Colgate",
                nombre: "ULTRASOFT",
                img: imgSensibilidad.producto.prodSensibilidad.prodSensibilidad_073,
            }
        ],
        beneficios: []
    },
  ]
}

export const Infantil = {
  "footer": "Infantil",
  "InformacionCabecera": {
    tipo: "producto",
    img: imgInfantil.cabecera,
    tituloSuperior: "Colgate",
    prefijo: "",
    nombre: "MINIONS PARA NIÑOS",
    sufijo: "",
    subTitulo: "Combate las caries y protege el esmalte con los productos infantiles Colgate Minions!",
    informacion: "",
    tituloSec: "BENEFICIOS:",
    beneficios: [
      { beneficio: "Cepillos con cerdas multi-nivel para limpiar dientes chicos y grande." },
      { beneficio: "Gel dental clínicamente probado para dar protección contra las caries." },
      { beneficio: "Enjuague bucal que limpia toda la boca, eliminando las partículas que pudieron haber quedado después del cepillado." },
    ],
    extra: "",
    productos: []
  },
  "ImagenesMenuBotones": imgInfantil.botones,
  "InformacionProductos": [
    {
      id: 1,
      tipo: "producto",
      img: imgInfantil.producto.prodInfantil_01,
      tituloSuperior: "Colgate Smiles",
      prefijo: "",
      nombre: "BARBIE - MINIONS",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Protección contra las caries, clínicamente probado" },
        { beneficio: "Protección del esmalte que fortalece y protege los dientes" },
        { beneficio: "Gel con delicioso sabor a tutti-frutti" },
        { beneficio: "Con flúor para niños" },
        { beneficio: "Viene en un cómodo tubo que es fácil de usar" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 2,
      tipo: "producto",
      img: imgInfantil.producto.prodInfantil_02,
      tituloSuperior: "Colgate Smiles",
      prefijo: "",
      nombre: "LIGA DE LA JUSTICIA",
      sufijo: "",
      subTitulo: "",
      informacion: "",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Protección contra las caries clínicamente probado" },
        { beneficio: "Protección del esmalte que fortalece y protege los dientes" },
        { beneficio: "Con los personajes de Batman y la Mujer Maravilla que alientan a los niños a cepillarse" },
        { beneficio: "Viene en un cómodo tubo que es fácil de usar" },
      ],
      extra: "",
      productos: []
    },
    {
      id: 3,
      tipo: "producto",
      img: imgInfantil.producto.prodInfantil_03,
      tituloSuperior: "Colgate Smiles",
      prefijo: "",
      nombre: "MY FIRST",
      sufijo: "",
      subTitulo: "sin flúor",
      informacion: "Es necesario brindar una protección dental a los más pequeños del hogar para evitar el desarrollo de enfermedades; con la Pasta Dental Colgate sin fluor podrás cepillar sus primeros y pequeños dientes desde los 6 hasta los 24 meses de edad.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Su fórmula es libre de flúor, podrás utilizarla con confianza y sin preocuparte por ocasionarle algún problema si llega a comerla por accidente." },
        { beneficio: "Tiene un suave y delicioso sabor a fruta para que tu hijo la disfrute, está libre de conservadores y colorantes artificiales." },
        { beneficio: "Su presentación de 50 gr (40 ml) es ideal para que la lleves siempre en tu pañalers." },
      ],
      extra: "*Recomendado para niños de 0 a 2 años.",
      productos: []
    },
    {
      id: 4,
      tipo: "producto",
      img: imgInfantil.producto.prodInfantil_04,
      tituloSuperior: "Colgate Smiles",
      prefijo: "",
      nombre: "KIDS",
      sufijo: "",
      subTitulo: "",
      informacion: "Crema dental Colgate Kids Fresantástico para dientes fuertes y protegidos. Hará más fácil la tarea de enseñar a los pequeños de la casa la importancia de una salud bucal adecuada y alentarlos a cepillarse las 3 veces recomendadas para evitar daño en sus pequeños dientes.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Su fórmula clínicamente comprobada para dar protección contra las caries, cuenta con una presentación en gel que hace menos espuma, permitiendo que los niños completen la tarea sin necesitar de un adulto ya que cuenta con la cantidad adecuada de fluoruro para los niños." },
      ],
      extra: "*Es apta para niños de 1 año en adelante.",
      productos: []
    },
    {
        id: 5,
        tipo: "imagenes",
        tituloSec: "",
        productos: [
            {
                tituloSuperior: "Colgate Smiles",
                nombre: "BARBIE",
                img: imgInfantil.producto.prodInfantil.prodInfantil_051,
            },
            {
                tituloSuperior: "Colgate Smiles",
                nombre: "BATMAN",
                img: imgInfantil.producto.prodInfantil.prodInfantil_052,
            },
            {
                tituloSuperior: "Colgate Smiles",
                nombre: "MUJER MARAVILLA",
                img: imgInfantil.producto.prodInfantil.prodInfantil_053,
            },
            {
                tituloSuperior: "Colgate Smiles",
                nombre: "MINIONS",
                img: imgInfantil.producto.prodInfantil.prodInfantil_054,
            }
        ],
        beneficios: []
    },
    {
      id: 6,
      tipo: "producto",
      img: imgInfantil.producto.prodInfantil_06,
      tituloSuperior: "Colgate",
      prefijo: "",
      nombre: "PLAX MINIONS",
      sufijo: "",
      subTitulo: "",
      informacion: "Enjuague bucal con flúor que ayuda a fortalecer el esmalte y brinda protección anticaries para los niños.",
      tituloSec: "BENEFICIOS:",
      beneficios: [
        { beneficio: "Ahora presentando por los personajes favoritos de tus hijos, los minions!" },
        { beneficio: "Limpia toda la boca, eliminando las partículas que pudieron haber quedado después del cepillado" },
        { beneficio: "Fun Bello Bubble Fruit, con sabor a chicle de frutas que los niños disfrutarán" },
      ],
      extra: "",
      productos: []
    },
  ]
}
/*
{
    id: 8,
    tipo: "",
    tipo: "producto",
    img: "",
    tituloSuperior: "",
    prefijo: "",
    nombre: "",
    sufijo: "",
    subTitulo: "",
    informacion: "",
    tituloSec: "ayuda a",
    beneficios: [
        { beneficio: "a" },
        { beneficio: "a" },
        { beneficio: "a" },
        { beneficio: "a" },
    ],
    extra: "",
    productos: []
},
*/